name: Build and Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      draft:
        description: 'Create as draft release'
        required: true
        default: true
        type: boolean
      version:
        description: 'Version name (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: keepass2file-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: keepass2file-darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: keepass2file-darwin-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref }}
          release_name: Release ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref }}
          draft: ${{ inputs.draft || false }}
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/app
          asset_name: ${{ matrix.binary_name }}
          asset_content_type: application/octet-stream
